### ISSUE TITLE
Pitch Deck feedback

### ISSUE THREAD

**Issue by sofa13** [DashDrop/DashDrop.github.io#3]
Hey Team #13  @toluolubode @MacLinh @meinaoria @haneenqasem98 , 

This is Sophie, one of your TAs for SEG1911. This issue I opened is just an easy way for me to give you feedback for your pitch deck based on what you submitted for deliverable 4. I haven't started marking deliverable 4, this feedback is just to help you guys before you present tomorrow!

Feedback:
- Your "the problem" slide can be split up into 3 slides
- You should indicate in writing that "Dashdrop" is the solution!
- The use case you included is a really good idea! The highlighting for the "use-case" title is a bit awkward
- For the "Value proposal" slide, I would recommend removing some or all text. for example `we are going to change the way business owners deliver their products` (*) can be simplified to bullet point such as `change the way products are delivered`, and in the presentation you can say the full sentence (*)
- What are you seeking? Investment, Customers, Talent, Users?
- Good start!

If you have any questions, just leave a comment in this issue and tag my github name @sofa13 :) Looking forward to seeing your presentation tomorrow!

Sophie

**Comment by caseyli** [comment]
@toluolubode @MacLinh @meinaoria @haneenqasem98 

Totally agree with a lot of what @sofa13 is saying. If you can convey it verbally, simplify your slides.

**Comment by toluolubode** [comment]
Thank you for the feedback, really helped our presentation.
